### ISSUE TITLE
Dog Filter Bug report

### ISSUE THREAD

**Issue by Komal-99** [akshitagupta15june/Face-X#331] opened 2021-03-13 16:34 UTC
**Describe the bug**
There is bug in Snapchat filter ---> Dog_filter. The dog filter detect some unknown face on wall while using the filter and put dog filter on it also. Also The Readme file of dog filter can be updated as the modules version written in requirement.txt file are very old and can't be easily run with python3 . And one point can be added in installation steps.

**To Reproduce**
1. Update requirements.txt
2. Found bud for detecting unknown face sometime and Filter changes so often in 1 sec  in loop
3. Updating Readme 

**Expected behavior**
Should detect only human face

**Actual behavior**

**Screenshots**

**Additional details**

**Comment by akshatvirmani** [comment] 2021-03-14 12:15
I would like to work on this issue. Please assign this to me.

**Comment by akshitagupta15june** [comment] 2021-03-15 15:27
assigning

**Comment by Nikita0509** [comment] 2021-04-07 13:44
If the issue is unsolved i would also like to work on this issue can u guide me how can i get started .

**Comment by Komal-99** [comment] 2021-04-07 17:45
@Nikita0509  this issue is open for all anyone can work on it. Btw  I am also doing and trying to handle some   version errors

**Comment by akshitagupta15june** [comment] 2021-04-09 18:01
are you still working on this issue?

**Comment by Nikita0509** [comment] 2021-04-10 09:27
I don't kn how to proceed with this issue

**Closed** 2021-05-24 05:32 UTC
Labels: Level0, bug, gssoc21
